# Generated by Django 6.0.6 on 2026-06-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('equipment_age_years', models.FloatField(default=10.0)),
                ('population', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_percent', models.FloatField(default=10.0)),
                ('elderly_percent', models.FloatField(default=15.0)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictor.gridzone')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('infra_type', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.gridzone')),
            ],
        ),
        migrations.CreateModel(
            name='OutageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wind_speed', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('equipment_age_years', models.FloatField()),
                ('outage_occurred', models.BooleanField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.gridzone')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wind_speed', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.gridzone')),
            ],
        ),
    ]
