# Generated by Django 6.0.6 on 2026-06-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_real_weather', models.BooleanField(default=False, help_text='Switch to real weather API (True) or simulation (False)')),
                ('openweather_api_key', models.CharField(blank=True, default='', help_text='Get from https://openweathermap.org/api', max_length=100)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
    ]
